{{- if and .Values.metrics.enabled .Values.metrics.prometheus.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "azimuth-capi-operator.fullname" . }}
  labels: {{ include "azimuth-capi-operator.labels" . | nindent 4 }}
spec:
  groups:
    - name: azimuth-capi-operator.rules
      rules:
        - alert: AzimuthKubernetesClusterNotReady
          expr: >-
            sum(azimuth_kube_cluster_phase{phase!="Ready"}) by(cluster_namespace, cluster_name) > 0
          for: 1h
          annotations:
            description: >-
              Kubernetes cluster
              {{ "{{" }} $labels.cluster_namespace {{ "}}" }}/{{ "{{" }} $labels.cluster_name {{ "}}" }}
              has been in a non-ready state for longer than one hour.
            summary: Kubernetes cluster has been in a non-ready state for more than one hour.
          labels:
            severity: warning

        - alert: AzimuthKubernetesAppNotDeployed
          expr: >-
            sum(azimuth_kube_app_phase{app_template=~".+",phase!="Deployed"}) by (app_namespace, app_name) > 0
          for: 1h
          annotations:
            description: >-
              Kubernetes app
              {{ "{{" }} $labels.app_namespace {{ "}}" }}/{{ "{{" }} $labels.app_name {{ "}}" }}
              has taken more than one hour to deploy.
            summary: Kubernetes app has taken more than one hour to deploy.
          labels:
            severity: warning

        - alert: AzimuthKubernetesNgnixIngressNotRemoved
          expr: >-
            sum(azimuth_kube_cluster_addon_phase{addon="ingress-nginx"}) by(cluster_namespace, cluster_name) > 0
          for: 5m
          annotations:
            description: >-
              Kubernetes cluster
              {{ "{{" }} $labels.cluster_namespace {{ "}}" }}/{{ "{{" }} $labels.cluster_name {{ "}}" }}
              still has ngnix-ingress deployed.
            summary: Kubernetes cluster still has nginx-ingress deployed.
          labels:
            severity: info

        - alert: AzimuthKubernetesDashboardNotRemoved
          expr: >-
            sum(azimuth_kube_cluster_addon_phase{addon="kubernetes-dashboard"}) by(cluster_namespace, cluster_name) > 0
          for: 5m
          annotations:
            description: >-
              Kubernetes cluster
              {{ "{{" }} $labels.cluster_namespace {{ "}}" }}/{{ "{{" }} $labels.cluster_name {{ "}}" }}
              still has kubernetes-dashboard deployed.
            summary: Kubernetes cluster still has kubernetes dashboard deployed.
          labels:
            severity: info
{{- end }}
